/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world_of_harry_potter_reveal_and_dual;

import javax.swing.JFrame;

/**
 *
 * @author Magical Me
 */
public class Duel1 extends javax.swing.JFrame {
   

    /**
     * Creates new form Duel1
     */
    public Duel1() {
        initComponents();
    }
    
    public Duel1(int score){
        initComponents();
        ScoreValueDisplayLabel.setText(String.valueOf(score));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ProceedToDuelButton = new javax.swing.JButton();
        ScoreDummy = new javax.swing.JLabel();
        ScoreValueDisplayLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        ProceedToDuelButton.setBackground(new java.awt.Color(255, 51, 51));
        ProceedToDuelButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ProceedToDuelButton.setText("Proceed to Duel >>>");
        ProceedToDuelButton.setOpaque(false);
        ProceedToDuelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedToDuelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ProceedToDuelButton);
        ProceedToDuelButton.setBounds(290, 100, 240, 31);

        ScoreDummy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ScoreDummy.setForeground(new java.awt.Color(255, 255, 255));
        ScoreDummy.setText("Score:");
        jPanel1.add(ScoreDummy);
        ScoreDummy.setBounds(620, 110, 58, 22);

        ScoreValueDisplayLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ScoreValueDisplayLabel.setForeground(new java.awt.Color(204, 0, 204));
        jPanel1.add(ScoreValueDisplayLabel);
        ScoreValueDisplayLabel.setBounds(690, 100, 100, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/Duelling bckground.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 750, 710);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProceedToDuelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedToDuelButtonActionPerformed
        // TODO add your handling code here:

        int score=Integer.parseInt(ScoreValueDisplayLabel.getText());
        JFrame newFrame=new DuelRound1(score);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProceedToDuelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Duel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Duel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Duel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Duel1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Duel1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ProceedToDuelButton;
    private javax.swing.JLabel ScoreDummy;
    private javax.swing.JLabel ScoreValueDisplayLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
