/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world_of_harry_potter_reveal_and_dual;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Magical Me
 */
public class HorntailDuel extends javax.swing.JFrame  {

    /**
     * Creates new form HorntailDuel
     */
    public HorntailDuel() {
        initComponents();
         this.setSize(892, 600);
    }

    HorntailDuel(int score) {
       initComponents();
       this.setSize(892, 869);
       ScoreValueDisplayLabel.setText(String.valueOf(score));
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        HarryScore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        HorntailScore = new javax.swing.JLabel();
        HarryAccioButton = new javax.swing.JButton();
        HarryHideButton = new javax.swing.JButton();
        HarryCollectEgg = new javax.swing.JButton();
        HorntailReleaseFireButton = new javax.swing.JButton();
        HorntailChaseButton = new javax.swing.JButton();
        HorntailBiteHarryButton = new javax.swing.JButton();
        ScoreDummy = new javax.swing.JLabel();
        ScoreValueDisplayLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Life:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(157, 320, 49, 28);

        HarryScore.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        HarryScore.setForeground(new java.awt.Color(255, 255, 255));
        HarryScore.setText("150");
        jPanel1.add(HarryScore);
        HarryScore.setBounds(207, 320, 36, 28);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Life:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(514, 320, 49, 28);

        HorntailScore.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        HorntailScore.setForeground(new java.awt.Color(255, 255, 255));
        HorntailScore.setText("150");
        jPanel1.add(HorntailScore);
        HorntailScore.setBounds(572, 320, 36, 28);

        HarryAccioButton.setBackground(new java.awt.Color(51, 51, 51));
        HarryAccioButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HarryAccioButton.setForeground(new java.awt.Color(0, 204, 204));
        HarryAccioButton.setText("Accio");
        HarryAccioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarryAccioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HarryAccioButton);
        HarryAccioButton.setBounds(40, 380, 280, 44);

        HarryHideButton.setBackground(new java.awt.Color(51, 51, 51));
        HarryHideButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HarryHideButton.setForeground(new java.awt.Color(0, 204, 204));
        HarryHideButton.setText("Hide");
        HarryHideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarryHideButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HarryHideButton);
        HarryHideButton.setBounds(40, 490, 280, 44);

        HarryCollectEgg.setBackground(new java.awt.Color(51, 51, 51));
        HarryCollectEgg.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HarryCollectEgg.setForeground(new java.awt.Color(0, 204, 204));
        HarryCollectEgg.setText("Collect Golden Egg");
        HarryCollectEgg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarryCollectEggActionPerformed(evt);
            }
        });
        jPanel1.add(HarryCollectEgg);
        HarryCollectEgg.setBounds(40, 440, 280, 44);

        HorntailReleaseFireButton.setBackground(new java.awt.Color(51, 51, 51));
        HorntailReleaseFireButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HorntailReleaseFireButton.setForeground(new java.awt.Color(0, 204, 204));
        HorntailReleaseFireButton.setText("Release Fire");
        HorntailReleaseFireButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorntailReleaseFireButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HorntailReleaseFireButton);
        HorntailReleaseFireButton.setBounds(460, 390, 230, 44);

        HorntailChaseButton.setBackground(new java.awt.Color(51, 51, 51));
        HorntailChaseButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HorntailChaseButton.setForeground(new java.awt.Color(0, 204, 204));
        HorntailChaseButton.setText("Chase");
        HorntailChaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorntailChaseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HorntailChaseButton);
        HorntailChaseButton.setBounds(460, 440, 230, 44);

        HorntailBiteHarryButton.setBackground(new java.awt.Color(51, 51, 51));
        HorntailBiteHarryButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HorntailBiteHarryButton.setForeground(new java.awt.Color(0, 204, 204));
        HorntailBiteHarryButton.setText("Bite Harry");
        HorntailBiteHarryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorntailBiteHarryButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HorntailBiteHarryButton);
        HorntailBiteHarryButton.setBounds(460, 490, 230, 44);

        ScoreDummy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ScoreDummy.setForeground(new java.awt.Color(255, 255, 255));
        ScoreDummy.setText("Score:");
        jPanel1.add(ScoreDummy);
        ScoreDummy.setBounds(573, 29, 90, 22);

        ScoreValueDisplayLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(ScoreValueDisplayLabel);
        ScoreValueDisplayLabel.setBounds(672, 29, 110, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/horntail_battle.gif"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(163, 90, 500, 179);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/fire.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 880, 560);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HarryHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarryHideButtonActionPerformed
        // TODO add your handling code here:
        int horntailLifeScore=Integer.parseInt(HorntailScore.getText());
        horntailLifeScore=horntailLifeScore-20;
        HorntailScore.setText(String.valueOf(horntailLifeScore));
        if(horntailLifeScore<=0){
            JOptionPane.showMessageDialog(null, "You have successfully dueled Hungarian Horntail Dragon!  Congratulations!");
            int score=Integer.parseInt(ScoreValueDisplayLabel.getText())+200;
            JOptionPane.showMessageDialog(null, " Your score is :"+score);
            if(score>1200){
            JFrame frame=new Congratulation();
            this.hide();
            frame.show();
        }
            if(score<=1200){
              
            JOptionPane.showMessageDialog(null, " Proceeding to the next reveal level");
              JFrame frame=new RevealL3Q1(score);
            this.hide();
            frame.show();
            }
        }
    }//GEN-LAST:event_HarryHideButtonActionPerformed

    private void HarryCollectEggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarryCollectEggActionPerformed
        // TODO add your handling code here:
        int horntailLifeScore=Integer.parseInt(HorntailScore.getText());
        horntailLifeScore=horntailLifeScore-150;
        HorntailScore.setText(String.valueOf(horntailLifeScore));
        if(horntailLifeScore<=0){
            JOptionPane.showMessageDialog(null, "You have successfully dueled Hungarian Horntail Dragon!  Congratulations!");
            int score=Integer.parseInt(ScoreValueDisplayLabel.getText())+200;
            JOptionPane.showMessageDialog(null, " Your score is :"+score);
            if(score>1200){
            JFrame frame=new Congratulation();
            this.hide();
            frame.show();
        }
            if(score<=1200){
              
            JOptionPane.showMessageDialog(null, " Proceeding to the next reveal level");
              JFrame frame=new RevealL3Q1(score);
            this.hide();
            frame.show();
            }
        }
        String points=String.valueOf(horntailLifeScore);
        HorntailScore.setText(points);
    }//GEN-LAST:event_HarryCollectEggActionPerformed

    private void HorntailReleaseFireButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorntailReleaseFireButtonActionPerformed
        // TODO add your handling code here:
        int harryScore=Integer.parseInt(HarryScore.getText());
        harryScore=harryScore-80;
        HarryScore.setText(String.valueOf(harryScore));
        if(harryScore<=0){
            int score=Integer.parseInt(ScoreValueDisplayLabel.getText()) - 500;
            JOptionPane.showMessageDialog(null, "You have been defeated!  Redirected to previous duel");
            JFrame frame=new DuelRound1(score);
            this.hide();
            frame.show();

        }
        String points=String.valueOf(harryScore);
        HarryScore.setText(points);
    }//GEN-LAST:event_HorntailReleaseFireButtonActionPerformed

    private void HorntailChaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorntailChaseButtonActionPerformed
        // TODO add your handling code here:
         int harryScore=Integer.parseInt(HarryScore.getText());
        harryScore=harryScore-10;
         HarryScore.setText(String.valueOf(harryScore));
        if(harryScore<=0){
            int score=Integer.parseInt(ScoreValueDisplayLabel.getText()) - 500;
            JOptionPane.showMessageDialog(null, "You have been defeated!  Redirected to previous duel");
            JFrame frame=new DuelRound1(score);
            this.hide();
            frame.show();

        }
        String points=String.valueOf(harryScore);
        HarryScore.setText(points);
    }//GEN-LAST:event_HorntailChaseButtonActionPerformed

    private void HorntailBiteHarryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorntailBiteHarryButtonActionPerformed
        // TODO add your handling code here:
         int harryScore=Integer.parseInt(HarryScore.getText());
        harryScore=harryScore-50;
        HarryScore.setText(String.valueOf(harryScore));
        if(harryScore<=0){
            int score=Integer.parseInt(ScoreValueDisplayLabel.getText()) - 500;
            JOptionPane.showMessageDialog(null, "You have been defeated!  Redirected to previous duel");
            JFrame frame=new DuelRound1(score);
            this.hide();
            frame.show();

        }
        String points=String.valueOf(harryScore);
        HarryScore.setText(points);
    }//GEN-LAST:event_HorntailBiteHarryButtonActionPerformed

    private void HarryAccioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarryAccioButtonActionPerformed
        // TODO add your handling code here:
        int horntailLifeScore=Integer.parseInt(HorntailScore.getText());
        horntailLifeScore=horntailLifeScore-50;
        HorntailScore.setText(String.valueOf(horntailLifeScore));
        if(horntailLifeScore<=0){
            JOptionPane.showMessageDialog(null, "You have successfully dueled Hungarian Horntail Dragon!  Congratulations!");
            int score=Integer.parseInt(ScoreValueDisplayLabel.getText())+200;
            JOptionPane.showMessageDialog(null, " Your score is :"+score);
            if(score>1200){
            JFrame frame=new Congratulation();
            this.hide();
            frame.show();
        }
            if(score<=1200){
              
            JOptionPane.showMessageDialog(null, " Proceeding to the next reveal level");
              JFrame frame=new RevealL3Q1(score);
            this.hide();
            frame.show();
            }
        }
        String points=String.valueOf(horntailLifeScore);
        HorntailScore.setText(points);
    }//GEN-LAST:event_HarryAccioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorntailDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorntailDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorntailDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorntailDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HorntailDuel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HarryAccioButton;
    private javax.swing.JButton HarryCollectEgg;
    private javax.swing.JButton HarryHideButton;
    private javax.swing.JLabel HarryScore;
    private javax.swing.JButton HorntailBiteHarryButton;
    private javax.swing.JButton HorntailChaseButton;
    private javax.swing.JButton HorntailReleaseFireButton;
    private javax.swing.JLabel HorntailScore;
    private javax.swing.JLabel ScoreDummy;
    private javax.swing.JLabel ScoreValueDisplayLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
