/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world_of_harry_potter_reveal_and_dual;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Magical Me
 */
public class RevealL1Q4 extends javax.swing.JFrame {
int score;
    /**
     * Creates new form RevealL1Q4
     */
    public RevealL1Q4() {
        initComponents();
    }
    public RevealL1Q4(int score){
        initComponents();
        ScoreValueDisplayLabel.setText(String.valueOf(score));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Question = new javax.swing.JLabel();
        AragogButton = new javax.swing.JButton();
        HippogriffButton = new javax.swing.JButton();
        BasiliskButton = new javax.swing.JButton();
        ScoreDummy = new javax.swing.JLabel();
        ScoreValueDisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(null);

        Question.setBackground(new java.awt.Color(255,255,255));
        Question.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        Question.setText("4) Monstor inside Chamber of Secrets is...");
        Question.setToolTipText("");
        jPanel2.add(Question);
        Question.setBounds(220, 30, 540, 50);

        AragogButton.setBackground(new java.awt.Color(0, 0, 0));
        AragogButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        AragogButton.setForeground(new java.awt.Color(255, 255, 255));
        AragogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/aragog.PNG"))); // NOI18N
        AragogButton.setText("Aragog");
        AragogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AragogButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AragogButton);
        AragogButton.setBounds(10, 90, 370, 260);

        HippogriffButton.setBackground(new java.awt.Color(0, 0, 0));
        HippogriffButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        HippogriffButton.setForeground(new java.awt.Color(255, 255, 255));
        HippogriffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/buckbeak.PNG"))); // NOI18N
        HippogriffButton.setText("Hippogriff");
        HippogriffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HippogriffButtonActionPerformed(evt);
            }
        });
        jPanel2.add(HippogriffButton);
        HippogriffButton.setBounds(570, 120, 370, 250);

        BasiliskButton.setBackground(new java.awt.Color(0, 0, 0));
        BasiliskButton.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        BasiliskButton.setForeground(new java.awt.Color(255, 255, 255));
        BasiliskButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/basilisk.PNG"))); // NOI18N
        BasiliskButton.setText("Basilisk");
        BasiliskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BasiliskButtonActionPerformed(evt);
            }
        });
        jPanel2.add(BasiliskButton);
        BasiliskButton.setBounds(340, 390, 240, 210);

        ScoreDummy.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        ScoreDummy.setText("Score:");
        ScoreDummy.setToolTipText("");
        jPanel2.add(ScoreDummy);
        ScoreDummy.setBounds(750, 20, 75, 29);

        ScoreValueDisplayLabel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        ScoreValueDisplayLabel.setToolTipText("");
        jPanel2.add(ScoreValueDisplayLabel);
        ScoreValueDisplayLabel.setBounds(830, 20, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 973, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AragogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AragogButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Wrong Answer!");
         score=Integer.parseInt(ScoreValueDisplayLabel.getText());
      JFrame next=new RevealCompleteImage(score);
        next.show();
        this.dispose();
    //    this.dispose();
        
    }//GEN-LAST:event_AragogButtonActionPerformed

    private void HippogriffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HippogriffButtonActionPerformed
        // TODO add your handling code here:
       JOptionPane.showMessageDialog(null, "Wrong Answer!");
         score=Integer.parseInt(ScoreValueDisplayLabel.getText());
      JFrame next=new RevealCompleteImage(score);
        next.show();
        this.dispose();
        
    }//GEN-LAST:event_HippogriffButtonActionPerformed

    private void BasiliskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BasiliskButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Correct!");
         score=50+Integer.parseInt(ScoreValueDisplayLabel.getText());
        System.out.println("Additional 50 points");
       JFrame newFrame=new RevealCompleteImage(score);
       newFrame.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_BasiliskButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevealL1Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevealL1Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevealL1Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevealL1Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevealL1Q4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AragogButton;
    private javax.swing.JButton BasiliskButton;
    private javax.swing.JButton HippogriffButton;
    private javax.swing.JLabel Question;
    private javax.swing.JLabel ScoreDummy;
    private javax.swing.JLabel ScoreValueDisplayLabel;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
