/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world_of_harry_potter_reveal_and_dual;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Magical Me
 */
public class RevealL1Q2 extends javax.swing.JFrame {
private int score;
    /**
     * Creates new form RevealL1Q2
     */
    public RevealL1Q2() {
        initComponents();
//        score=new RevealL1Q1().getScore();
//        JOptionPane.showMessageDialog(null,score);
        
    }
    
    public RevealL1Q2(int score){
        initComponents();
        ScoreValueDisplayLabel.setText(String.valueOf(score));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ScoreValueDisplayLabel = new javax.swing.JLabel();
        FletcherButton = new javax.swing.JButton();
        FilchButton = new javax.swing.JButton();
        HagridButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        ScoreValueDisplayLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jPanel2.add(ScoreValueDisplayLabel);
        ScoreValueDisplayLabel.setBounds(850, 50, 110, 30);

        FletcherButton.setBackground(new java.awt.Color(0, 0, 0));
        FletcherButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        FletcherButton.setForeground(new java.awt.Color(0, 255, 255));
        FletcherButton.setText("Mundungus Fletcher");
        FletcherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FletcherButtonActionPerformed(evt);
            }
        });
        jPanel2.add(FletcherButton);
        FletcherButton.setBounds(300, 190, 470, 210);

        FilchButton.setBackground(new java.awt.Color(0, 0, 0));
        FilchButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        FilchButton.setForeground(new java.awt.Color(0, 255, 255));
        FilchButton.setText("Argus Filch");
        FilchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(FilchButton);
        FilchButton.setBounds(580, 430, 400, 230);

        HagridButton.setBackground(new java.awt.Color(0, 0, 0));
        HagridButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HagridButton.setForeground(new java.awt.Color(0, 255, 255));
        HagridButton.setText("Rubeus Hagrid");
        HagridButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HagridButtonActionPerformed(evt);
            }
        });
        jPanel2.add(HagridButton);
        HagridButton.setBounds(10, 440, 440, 37);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Round 1: Reveal");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(440, 20, 140, 40);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setText("2) Who is also called the \"Keeper of Keys\" at Hogwarts?");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 110, 650, 22);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setText("SCORE:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(730, 60, 80, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FletcherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FletcherButtonActionPerformed
        // TODO add your handling code here:
           score=Integer.parseInt(ScoreValueDisplayLabel.getText());
         JOptionPane.showMessageDialog(null, "Wrong answer");
            JFrame newFrame=new RevealL1Q3(score);
            newFrame.show();
            this.dispose();
    }//GEN-LAST:event_FletcherButtonActionPerformed

    private void FilchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilchButtonActionPerformed
        // TODO add your handling code here:
        score=Integer.parseInt(ScoreValueDisplayLabel.getText());
         JOptionPane.showMessageDialog(null, "Wrong answer");
            JFrame newFrame=new RevealL1Q3(score);
            newFrame.show();
            this.dispose();
    }//GEN-LAST:event_FilchButtonActionPerformed

    private void HagridButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HagridButtonActionPerformed
        // TODO add your handling code here:
        score=50+Integer.parseInt(ScoreValueDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Correct");
       JFrame newFrame=new RevealL1Q3(score);
       newFrame.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_HagridButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevealL1Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevealL1Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevealL1Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevealL1Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevealL1Q2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FilchButton;
    private javax.swing.JButton FletcherButton;
    private javax.swing.JButton HagridButton;
    private javax.swing.JLabel ScoreValueDisplayLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
