/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world_of_harry_potter_reveal_and_dual;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Magical Me
 */
public class RevealL3Q4 extends javax.swing.JFrame {
    private int score;

    /**
     * Creates new form RevealL3Q4
     */
    public RevealL3Q4() {
        initComponents();
    }
    
    public RevealL3Q4(int score){
        initComponents();
        ScoreDisplayLabel.setText(String.valueOf(score));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ScoreDisplayLabel = new javax.swing.JLabel();
        ReductoButton = new javax.swing.JButton();
        AscendioButton = new javax.swing.JButton();
        AnswerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        ScoreDisplayLabel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jPanel2.add(ScoreDisplayLabel);
        ScoreDisplayLabel.setBounds(800, 40, 120, 40);

        ReductoButton.setBackground(new java.awt.Color(0, 0, 0));
        ReductoButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        ReductoButton.setForeground(new java.awt.Color(255, 255, 255));
        ReductoButton.setText("Reducto");
        ReductoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReductoButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ReductoButton);
        ReductoButton.setBounds(340, 320, 350, 100);

        AscendioButton.setBackground(new java.awt.Color(0, 0, 0));
        AscendioButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        AscendioButton.setForeground(new java.awt.Color(255, 255, 255));
        AscendioButton.setText("Ascendio");
        AscendioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AscendioButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AscendioButton);
        AscendioButton.setBounds(660, 480, 300, 90);

        AnswerButton.setBackground(new java.awt.Color(0, 0, 0));
        AnswerButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        AnswerButton.setForeground(new java.awt.Color(255, 255, 255));
        AnswerButton.setText("Ridikulous");
        AnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AnswerButton);
        AnswerButton.setBounds(50, 190, 320, 90);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setText("Round 3 : Reveal");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(440, 20, 210, 40);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setText("4) What is the spell to control a boggart?");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(300, 120, 480, 29);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setText("SCORE:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(700, 50, 100, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReductoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReductoButtonActionPerformed
        // TODO add your handling code here:
        int score=Integer.parseInt(ScoreDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Wrong answer");
        JFrame newFrame=new RevealCompleteImage3(score);
        newFrame.show();
        this.dispose();
    }//GEN-LAST:event_ReductoButtonActionPerformed

    private void AscendioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AscendioButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        score=Integer.parseInt(ScoreDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Wrong Answer!");
         JFrame newFrame=new RevealCompleteImage3(score);
        newFrame.setVisible(true);
    }//GEN-LAST:event_AscendioButtonActionPerformed

    private void AnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButtonActionPerformed
        // TODO add your handling code here:
        score=Integer.parseInt(ScoreDisplayLabel.getText())+100;
        JOptionPane.showMessageDialog(null, "Correct");
        JFrame newFrame=new RevealCompleteImage3(score);
        newFrame.show();
        this.dispose();
    }//GEN-LAST:event_AnswerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevealL3Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevealL3Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevealL3Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevealL3Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevealL3Q4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnswerButton;
    private javax.swing.JButton AscendioButton;
    private javax.swing.JButton ReductoButton;
    private javax.swing.JLabel ScoreDisplayLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
