/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world_of_harry_potter_reveal_and_dual;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author atomar
 */
public class RevealL2Q2 extends javax.swing.JFrame {
private int score;
    /**
     * Creates new form RevealL2Q2
     */
    public RevealL2Q2() {
        initComponents();
    }

   public RevealL2Q2(int score){
        initComponents();
        ScoreValueDisplayLabel.setText(String.valueOf(score));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ScoreValueDisplayLabel = new javax.swing.JLabel();
        FletcherButton = new javax.swing.JButton();
        FilchButton = new javax.swing.JButton();
        HagridButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        ScoreValueDisplayLabel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        ScoreValueDisplayLabel.setForeground(new java.awt.Color(102, 255, 102));
        jPanel2.add(ScoreValueDisplayLabel);
        ScoreValueDisplayLabel.setBounds(820, 60, 130, 30);

        FletcherButton.setBackground(new java.awt.Color(0, 0, 0));
        FletcherButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        FletcherButton.setForeground(new java.awt.Color(0, 255, 255));
        FletcherButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/Sword.jpg"))); // NOI18N
        FletcherButton.setText("Griffindor Sword");
        FletcherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FletcherButtonActionPerformed(evt);
            }
        });
        jPanel2.add(FletcherButton);
        FletcherButton.setBounds(40, 160, 470, 140);

        FilchButton.setBackground(new java.awt.Color(0, 0, 0));
        FilchButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        FilchButton.setForeground(new java.awt.Color(0, 255, 255));
        FilchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/diadem.jpg"))); // NOI18N
        FilchButton.setText("Ravenclaw diadem");
        FilchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilchButtonActionPerformed(evt);
            }
        });
        jPanel2.add(FilchButton);
        FilchButton.setBounds(480, 310, 490, 150);

        HagridButton.setBackground(new java.awt.Color(0, 0, 0));
        HagridButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HagridButton.setForeground(new java.awt.Color(0, 255, 255));
        HagridButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/cloak.jpg"))); // NOI18N
        HagridButton.setText("Invisibility Cloak");
        HagridButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HagridButtonActionPerformed(evt);
            }
        });
        jPanel2.add(HagridButton);
        HagridButton.setBounds(40, 480, 500, 140);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Round 2: Reveal");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(440, 20, 140, 40);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setText("2) Which one of these is a deathly hallow?");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(210, 100, 650, 29);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setText("SCORE:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(710, 60, 100, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FletcherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FletcherButtonActionPerformed
        // TODO add your handling code here:
        score=Integer.parseInt(ScoreValueDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Wrong answer");
        JFrame newFrame=new RevealL2Q3(score);
        newFrame.show();
        this.dispose();
    }//GEN-LAST:event_FletcherButtonActionPerformed

    private void FilchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilchButtonActionPerformed
        // TODO add your handling code here:
        score=Integer.parseInt(ScoreValueDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Wrong answer");
        JFrame newFrame=new RevealL2Q3(score);
        newFrame.show();
        this.dispose();
    }//GEN-LAST:event_FilchButtonActionPerformed

    private void HagridButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HagridButtonActionPerformed
        // TODO add your handling code here:
        score=100+Integer.parseInt(ScoreValueDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Correct");
        JFrame newFrame=new RevealL2Q3(score);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HagridButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevealL2Q2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FilchButton;
    private javax.swing.JButton FletcherButton;
    private javax.swing.JButton HagridButton;
    private javax.swing.JLabel ScoreValueDisplayLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
