/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world_of_harry_potter_reveal_and_dual;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author atomar
 */
public class RevealL2Q3 extends javax.swing.JFrame {
 int score;
    /**
     * Creates new form RevealL2Q3
     */
    public RevealL2Q3() {
        initComponents();
    }

   public RevealL2Q3(int score){
        initComponents();
        ScoreDisplayLabel.setText(String.valueOf(score));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ScoreDisplayLabel = new javax.swing.JLabel();
        DumbeldoreButton = new javax.swing.JButton();
        SiriusButton = new javax.swing.JButton();
        LupinButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setForeground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(null);

        ScoreDisplayLabel.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jPanel2.add(ScoreDisplayLabel);
        ScoreDisplayLabel.setBounds(730, 40, 100, 40);

        DumbeldoreButton.setBackground(new java.awt.Color(0, 0, 0));
        DumbeldoreButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        DumbeldoreButton.setForeground(new java.awt.Color(255, 255, 255));
        DumbeldoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/Elder_Wand.png"))); // NOI18N
        DumbeldoreButton.setText("Elder Wand");
        DumbeldoreButton.setToolTipText("");
        DumbeldoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DumbeldoreButtonActionPerformed(evt);
            }
        });
        jPanel2.add(DumbeldoreButton);
        DumbeldoreButton.setBounds(50, 200, 370, 160);

        SiriusButton.setBackground(new java.awt.Color(0, 0, 0));
        SiriusButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        SiriusButton.setForeground(new java.awt.Color(255, 255, 255));
        SiriusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/diary.jpg"))); // NOI18N
        SiriusButton.setText("Riddle's diary");
        SiriusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiriusButtonActionPerformed(evt);
            }
        });
        jPanel2.add(SiriusButton);
        SiriusButton.setBounds(460, 160, 400, 260);

        LupinButton.setBackground(new java.awt.Color(0, 0, 0));
        LupinButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        LupinButton.setForeground(new java.awt.Color(255, 255, 255));
        LupinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/resurrection_stone.jpg"))); // NOI18N
        LupinButton.setText("Resurrection stone");
        LupinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LupinButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LupinButton);
        LupinButton.setBounds(40, 440, 430, 160);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setText("Round 2: Reveal");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(350, 20, 210, 40);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel2.setText("3) Which one of these is horcrux?");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(120, 100, 400, 29);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel3.setText("SCORE:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(610, 50, 120, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 895, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DumbeldoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DumbeldoreButtonActionPerformed
        // TODO add your handling code here:
        score=Integer.parseInt(ScoreDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Wrong answer");
        JFrame newFrame=new RevealL2Q4(score);
        newFrame.show();
        this.dispose();
    }//GEN-LAST:event_DumbeldoreButtonActionPerformed

    private void SiriusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiriusButtonActionPerformed
        // TODO add your handling code here:

        score=100+Integer.parseInt(ScoreDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "You have gained "  + score+" points ");
        JFrame newFrame=new RevealL2Q4(score);
        newFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SiriusButtonActionPerformed

    private void LupinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LupinButtonActionPerformed
        // TODO add your handling code here:
        score=Integer.parseInt(ScoreDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Wrong answer");
        JFrame newFrame=new RevealL2Q4(score);
        newFrame.show();
        this.dispose();
    }//GEN-LAST:event_LupinButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevealL2Q3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DumbeldoreButton;
    private javax.swing.JButton LupinButton;
    private javax.swing.JLabel ScoreDisplayLabel;
    private javax.swing.JButton SiriusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
