/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world_of_harry_potter_reveal_and_dual;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Magical Me
 */
public class RevealL2Q1 extends javax.swing.JFrame {
    private int score;

    /**
     * Creates new form RevealL2Q1
     */
    public RevealL2Q1() {
        initComponents();
        score=0;
    }
      public RevealL2Q1(int score){
        initComponents();
        ScoreDisplayLabel.setText(String.valueOf(score));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ScoreDisplayLabel = new javax.swing.JLabel();
        AguamentiButton = new javax.swing.JButton();
        AnswerButton = new javax.swing.JButton();
        ExpelliarmusButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        ScoreDisplayLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        ScoreDisplayLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ScoreDisplayLabel);
        ScoreDisplayLabel.setBounds(770, 40, 120, 40);

        AguamentiButton.setBackground(new java.awt.Color(0, 0, 0));
        AguamentiButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        AguamentiButton.setForeground(new java.awt.Color(255, 255, 255));
        AguamentiButton.setText("Aguamenti");
        AguamentiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguamentiButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AguamentiButton);
        AguamentiButton.setBounds(280, 310, 350, 100);

        AnswerButton.setBackground(new java.awt.Color(0, 0, 0));
        AnswerButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        AnswerButton.setForeground(new java.awt.Color(255, 255, 255));
        AnswerButton.setText("Lecornum Inflamorae");
        AnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AnswerButton);
        AnswerButton.setBounds(10, 180, 300, 90);

        ExpelliarmusButton.setBackground(new java.awt.Color(0, 0, 0));
        ExpelliarmusButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        ExpelliarmusButton.setForeground(new java.awt.Color(255, 255, 255));
        ExpelliarmusButton.setText("Expelliarmus");
        ExpelliarmusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpelliarmusButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ExpelliarmusButton);
        ExpelliarmusButton.setBounds(590, 460, 320, 90);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Round 2: Reveal");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(440, 20, 140, 40);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setText("1) Pick the spell that generates fire:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 110, 650, 22);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setText("SCORE:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(700, 50, 80, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AguamentiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguamentiButtonActionPerformed
        // TODO add your handling code here:
        score=Integer.parseInt(ScoreDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Wrong answer");
        JFrame newFrame=new RevealL2Q2(score);
        newFrame.show();
        this.dispose();
    }//GEN-LAST:event_AguamentiButtonActionPerformed

    private void AnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        score=Integer.parseInt(ScoreDisplayLabel.getText())+100;
        JOptionPane.showMessageDialog(null, "You have gained 100 points ");
        JFrame newFrame=new RevealL2Q2(score);
        newFrame.setVisible(true);
    }//GEN-LAST:event_AnswerButtonActionPerformed

    private void ExpelliarmusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpelliarmusButtonActionPerformed
        // TODO add your handling code here:
        score=Integer.parseInt(ScoreDisplayLabel.getText());
        JOptionPane.showMessageDialog(null, "Wrong answer");
        JFrame newFrame=new RevealL1Q2(score);
        newFrame.show();
        this.dispose();
    }//GEN-LAST:event_ExpelliarmusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RevealL2Q1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RevealL2Q1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AguamentiButton;
    private javax.swing.JButton AnswerButton;
    private javax.swing.JButton ExpelliarmusButton;
    private javax.swing.JLabel ScoreDisplayLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
