/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package world_of_harry_potter_reveal_and_dual;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Magical Me
 */
public class SnapeDuel extends javax.swing.JFrame {

    /**
     * Creates new form SnapeDuel
     */
    public SnapeDuel() {
        initComponents();
        this.setSize(974, 750);
    }
   public SnapeDuel(int score){
       initComponents();
       ScoreValueDisplayLabel.setText(String.valueOf(score));
        this.setSize(974, 750);
       
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HarryScore = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        SnapeScore = new javax.swing.JLabel();
        HarrySectumsemptraButton = new javax.swing.JButton();
        HarryDuroButton = new javax.swing.JButton();
        HarryStupefyButton = new javax.swing.JButton();
        SnapeLegilimensButton = new javax.swing.JButton();
        SnapeAvadaKedavraButton = new javax.swing.JButton();
        SnapeSectumseptraButton = new javax.swing.JButton();
        ScoreDummy = new javax.swing.JLabel();
        ScoreValueDisplayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/harry giffy.gif"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/world_of_harry_potter_reveal_and_dual/snape.gif"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Life:");

        HarryScore.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        HarryScore.setText("150");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setText("Life:");

        SnapeScore.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        SnapeScore.setText("150");

        HarrySectumsemptraButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HarrySectumsemptraButton.setText("Sectumsemptra");
        HarrySectumsemptraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarrySectumsemptraButtonActionPerformed(evt);
            }
        });

        HarryDuroButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HarryDuroButton.setText("Duro");
        HarryDuroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarryDuroButtonActionPerformed(evt);
            }
        });

        HarryStupefyButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        HarryStupefyButton.setText("Stupefy");
        HarryStupefyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarryStupefyButtonActionPerformed(evt);
            }
        });

        SnapeLegilimensButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        SnapeLegilimensButton.setText("Legilimens");
        SnapeLegilimensButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnapeLegilimensButtonActionPerformed(evt);
            }
        });

        SnapeAvadaKedavraButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        SnapeAvadaKedavraButton.setText("Avada Kedavra");
        SnapeAvadaKedavraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnapeAvadaKedavraButtonActionPerformed(evt);
            }
        });

        SnapeSectumseptraButton.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        SnapeSectumseptraButton.setText("Sectumsemptra");
        SnapeSectumseptraButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnapeSectumseptraButtonActionPerformed(evt);
            }
        });

        ScoreDummy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ScoreDummy.setText("Score:");

        ScoreValueDisplayLabel.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ScoreDummy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ScoreValueDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HarryScore))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(HarrySectumsemptraButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HarryStupefyButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HarryDuroButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SnapeScore)
                                .addGap(140, 140, 140)))
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SnapeSectumseptraButton, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(SnapeAvadaKedavraButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SnapeLegilimensButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ScoreValueDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScoreDummy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SnapeScore)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(HarryScore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SnapeLegilimensButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HarrySectumsemptraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HarryStupefyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SnapeAvadaKedavraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HarryDuroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SnapeSectumseptraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 980, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HarrySectumsemptraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarrySectumsemptraButtonActionPerformed
        // TODO add your handling code here:
        int snapescore=Integer.parseInt(SnapeScore.getText());
        snapescore=snapescore-50;
        if(snapescore<=0){
            JOptionPane.showMessageDialog(null, "You have successfully defeated Snape!  Congratulations!");
            int score=Integer.parseInt(ScoreValueDisplayLabel.getText())+200;
               if(score>1200){
            JFrame frame=new Congratulation();
            this.hide();
            frame.show();
        }
            if(score<=1200){
              
            JOptionPane.showMessageDialog(null, " Proceeding to the next reveal level");
              JFrame frame=new RevealL3Q1(score);
            this.hide();
            frame.show();
            }
        }
        String points=String.valueOf(snapescore);
        SnapeScore.setText(points);

    }//GEN-LAST:event_HarrySectumsemptraButtonActionPerformed

    private void HarryDuroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarryDuroButtonActionPerformed
        // TODO add your handling code here:
         int snapescore=Integer.parseInt(SnapeScore.getText());
        snapescore=snapescore-70;
        if(snapescore<=0){
            JOptionPane.showMessageDialog(null, "You have successfully defeated Snape!  Congratulations!");
            int score=Integer.parseInt(ScoreValueDisplayLabel.getText())+200;
               if(score>1200){
            JFrame frame=new Congratulation();
            this.hide();
            frame.show();
        }
            if(score<=1200){
              
            JOptionPane.showMessageDialog(null, " Proceeding to the next reveal level");
              JFrame frame=new RevealL3Q1(score);
            this.hide();
            frame.show();
            }
        }
        String points=String.valueOf(snapescore);
        SnapeScore.setText(points);
    }//GEN-LAST:event_HarryDuroButtonActionPerformed

    private void HarryStupefyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarryStupefyButtonActionPerformed
        // TODO add your handling code here:
         int snapescore=Integer.parseInt(SnapeScore.getText());
        snapescore=snapescore-30;
        if(snapescore<=0){
            JOptionPane.showMessageDialog(null, "You have successfully defeated Snape!  Congratulations!");
            int score=Integer.parseInt(ScoreValueDisplayLabel.getText())+200;
              if(score>1200){
            JFrame frame=new Congratulation();
            this.hide();
            frame.show();
        }
              if(score<=1200){
              
            JOptionPane.showMessageDialog(null, " Proceeding to the next reveal level");
              JFrame frame=new RevealL3Q1(score);
            this.hide();
            frame.show();
            }
        }
        String points=String.valueOf(snapescore);
        SnapeScore.setText(points);
    }//GEN-LAST:event_HarryStupefyButtonActionPerformed

    private void SnapeLegilimensButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnapeLegilimensButtonActionPerformed
        // TODO add your handling code here:
        int harryScore=Integer.parseInt(HarryScore.getText());
        harryScore=harryScore-50;
        int score=Integer.parseInt(ScoreValueDisplayLabel.getText())-500;
        if(harryScore<=0){
            JOptionPane.showMessageDialog(null, "You have been defeated!  You will be redirected to previous duel round!");
            JFrame frame=new Duel1(score);
            frame.setVisible(true);
           this.dispose();
        }
        String points=String.valueOf(harryScore);
        HarryScore.setText(points);
    }//GEN-LAST:event_SnapeLegilimensButtonActionPerformed

    private void SnapeAvadaKedavraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnapeAvadaKedavraButtonActionPerformed
        // TODO add your handling code here:
       int harryScore=Integer.parseInt(HarryScore.getText());
        harryScore=harryScore-150;
        int score=Integer.parseInt(ScoreValueDisplayLabel.getText())-500;
        if(harryScore<=0){
            JOptionPane.showMessageDialog(null, "You have been defeated!  You will redirected to previous duel round!");
            JFrame frame=new Duel1(score);
            frame.setVisible(true);
           this.dispose();
        }
        String points=String.valueOf(harryScore);
        HarryScore.setText(points);
    }//GEN-LAST:event_SnapeAvadaKedavraButtonActionPerformed

    private void SnapeSectumseptraButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnapeSectumseptraButtonActionPerformed
        // TODO add your handling code here:
       int harryScore=Integer.parseInt(HarryScore.getText());
        harryScore=harryScore-80;
        int score=Integer.parseInt(ScoreValueDisplayLabel.getText())-500;
        if(harryScore<=0){
            JOptionPane.showMessageDialog(null, "You have been defeated!  You will be redirected to previous duel round!");
            JFrame frame=new Duel1(score);
            frame.setVisible(true);
           this.dispose();
        }
        String points=String.valueOf(harryScore);
        HarryScore.setText(points);
    }//GEN-LAST:event_SnapeSectumseptraButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SnapeDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SnapeDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SnapeDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SnapeDuel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SnapeDuel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HarryDuroButton;
    private javax.swing.JLabel HarryScore;
    private javax.swing.JButton HarrySectumsemptraButton;
    private javax.swing.JButton HarryStupefyButton;
    private javax.swing.JLabel ScoreDummy;
    private javax.swing.JLabel ScoreValueDisplayLabel;
    private javax.swing.JButton SnapeAvadaKedavraButton;
    private javax.swing.JButton SnapeLegilimensButton;
    private javax.swing.JLabel SnapeScore;
    private javax.swing.JButton SnapeSectumseptraButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
